# Docker Desktop - Doesn't have support...
# TODO: PROD - When deployed in cloud enable this + kube-apiserver --encryption-provider-config=/etc/kubernetes/encryption-config.yaml
apiVersion: encryption.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - aesgcm:
          keys:
            - name: key1
              secret: R1YhkgigOCP2mQHPJbBegw==
      - identity: {}
