apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8580 # Change from 80
      targetPort: 80 # Keep this as the container port
    - name: https
      port: 8553 # Change from 443
      targetPort: 443 # Keep this as the container port
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: restrict-access-to-local-ingress
#   namespace: ingress-nginx
# spec:
#   podSelector:
#     matchLabels:
#       app.kubernetes.io/name: ingress-nginx
#   policyTypes:
#     - Ingress
#   ingress:
#     - from:
#         - ipBlock:
#             cidr: 192.168.1.0/24
