apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ui-ingress
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
    kubernetes.io/ingressClassName: "nginx"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: dev.grafana.api.socigy.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
  tls:
    - secretName: grafana-tls-secret
      hosts:
        - dev.grafana.api.socigy.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-ui-ingress
  namespace: vault
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
    kubernetes.io/ingressClassName: "nginx"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: vault.api.socigy.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault
                port:
                  number: 8200
  tls:
    - secretName: vault-tls-ingress-secret
      hosts:
        - vault.api.socigy.com
