// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Socigy.Microservices.Auth.Resources.EmailTemplates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Business\socigy\server\microservices\Socigy.Microservices.Auth\Resources\EmailTemplates\CodeVerificationTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class CodeVerificationTemplate : CodeVerificationTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org" +
                    "/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xh" +
                    "tml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:" +
                    "office:office\" lang=\"en\">\r\n<head>\r\n<title></title>\r\n<meta charset=\"UTF-8\" />\r\n<m" +
                    "eta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n<!--[if !ms" +
                    "o]>-->\r\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n<!--<![endif]--" +
                    ">\r\n<meta name=\"x-apple-disable-message-reformatting\" content=\"\" />\r\n<meta conten" +
                    "t=\"target-densitydpi=device-dpi\" name=\"viewport\" />\r\n<meta content=\"true\" name=\"" +
                    "HandheldFriendly\" />\r\n<meta content=\"width=device-width\" name=\"viewport\" />\r\n<me" +
                    "ta name=\"format-detection\" content=\"telephone=no, date=no, address=no, email=no," +
                    " url=no\" />\r\n<style type=\"text/css\">\r\ntable {\r\nborder-collapse: separate;\r\ntable" +
                    "-layout: fixed;\r\nmso-table-lspace: 0pt;\r\nmso-table-rspace: 0pt\r\n}\r\ntable td {\r\nb" +
                    "order-collapse: collapse\r\n}\r\n.ExternalClass {\r\nwidth: 100%\r\n}\r\n.ExternalClass,\r\n" +
                    ".ExternalClass p,\r\n.ExternalClass span,\r\n.ExternalClass font,\r\n.ExternalClass td" +
                    ",\r\n.ExternalClass div {\r\nline-height: 100%\r\n}\r\nbody, a, li, p, h1, h2, h3 {\r\n-ms" +
                    "-text-size-adjust: 100%;\r\n-webkit-text-size-adjust: 100%;\r\n}\r\nhtml {\r\n-webkit-te" +
                    "xt-size-adjust: none !important\r\n}\r\nbody, #innerTable {\r\n-webkit-font-smoothing:" +
                    " antialiased;\r\n-moz-osx-font-smoothing: grayscale\r\n}\r\n#innerTable img+div {\r\ndis" +
                    "play: none;\r\ndisplay: none !important\r\n}\r\nimg {\r\nMargin: 0;\r\npadding: 0;\r\n-ms-in" +
                    "terpolation-mode: bicubic\r\n}\r\nh1, h2, h3, p, a {\r\nline-height: inherit;\r\noverflo" +
                    "w-wrap: normal;\r\nwhite-space: normal;\r\nword-break: break-word\r\n}\r\na {\r\ntext-deco" +
                    "ration: none\r\n}\r\nh1, h2, h3, p {\r\nmin-width: 100%!important;\r\nwidth: 100%!import" +
                    "ant;\r\nmax-width: 100%!important;\r\ndisplay: inline-block!important;\r\nborder: 0;\r\n" +
                    "padding: 0;\r\nmargin: 0\r\n}\r\na[x-apple-data-detectors] {\r\ncolor: inherit !importan" +
                    "t;\r\ntext-decoration: none !important;\r\nfont-size: inherit !important;\r\nfont-fami" +
                    "ly: inherit !important;\r\nfont-weight: inherit !important;\r\nline-height: inherit " +
                    "!important\r\n}\r\nu + #body a {\r\ncolor: inherit;\r\ntext-decoration: none;\r\nfont-size" +
                    ": inherit;\r\nfont-family: inherit;\r\nfont-weight: inherit;\r\nline-height: inherit;\r" +
                    "\n}\r\na[href^=\"mailto\"],\r\na[href^=\"tel\"],\r\na[href^=\"sms\"] {\r\ncolor: inherit;\r\ntext" +
                    "-decoration: none\r\n}\r\n</style>\r\n<style type=\"text/css\">\r\n@media (min-width: 481p" +
                    "x) {\r\n.hd { display: none!important }\r\n}\r\n</style>\r\n<style type=\"text/css\">\r\n@me" +
                    "dia (max-width: 480px) {\r\n.hm { display: none!important }\r\n}\r\n</style>\r\n<style t" +
                    "ype=\"text/css\">\r\n@media (max-width: 480px) {\r\n.t61,.t66{mso-line-height-alt:0px!" +
                    "important;line-height:0!important;display:none!important}.t62{padding:40px!impor" +
                    "tant}.t64{border-radius:0!important;width:480px!important}.t16,.t46,.t59,.t9{wid" +
                    "th:398px!important}.t52{text-align:left!important}.t51{vertical-align:top!import" +
                    "ant;width:600px!important}\r\n}\r\n</style>\r\n<!--[if !mso]>-->\r\n<link href=\"https://" +
                    "fonts.googleapis.com/css2?family=Montserrat:wght@700&amp;family=Sofia+Sans:wght@" +
                    "700&amp;family=Open+Sans:wght@400;700&amp;display=swap\" rel=\"stylesheet\" type=\"t" +
                    "ext/css\" />\r\n<!--<![endif]-->\r\n<!--[if mso]>\r\n<xml>\r\n<o:OfficeDocumentSettings>\r" +
                    "\n<o:AllowPNG/>\r\n<o:PixelsPerInch>96</o:PixelsPerInch>\r\n</o:OfficeDocumentSetting" +
                    "s>\r\n</xml>\r\n<![endif]-->\r\n</head>\r\n<body id=body class=t69 style=\"min-width:100%" +
                    ";Margin:0px;padding:0px;background-color:#FFFFFF;\"><div class=t68 style=\"backgro" +
                    "und-color:#FFFFFF;\"><table role=presentation width=100% cellpadding=0 cellspacin" +
                    "g=0 border=0 align=center><tr><td class=t67 style=\"font-size:0;line-height:0;mso" +
                    "-line-height-rule:exactly;background-color:#FFFFFF;\" valign=top align=center>\r\n<" +
                    "!--[if mso]>\r\n<v:background xmlns:v=\"urn:schemas-microsoft-com:vml\" fill=\"true\" " +
                    "stroke=\"false\">\r\n<v:fill color=#FFFFFF/>\r\n</v:background>\r\n<![endif]-->\r\n<table " +
                    "role=presentation width=100% cellpadding=0 cellspacing=0 border=0 align=center i" +
                    "d=innerTable><tr><td><div class=t61 style=\"mso-line-height-rule:exactly;mso-line" +
                    "-height-alt:50px;line-height:50px;font-size:1px;display:block;\">&nbsp;&nbsp;</di" +
                    "v></td></tr><tr><td align=center>\r\n<table class=t65 role=presentation cellpaddin" +
                    "g=0 cellspacing=0 style=\"Margin-left:auto;Margin-right:auto;\">\r\n<tr>\r\n<!--[if ms" +
                    "o]>\r\n<td width=600 class=t64 style=\"background-color:#FFFFFF;border:1px solid #E" +
                    "BEBEB;overflow:hidden;width:600px;border-radius:3px 3px 3px 3px;\">\r\n<![endif]-->" +
                    "\r\n<!--[if !mso]>-->\r\n<td class=t64 style=\"background-color:#FFFFFF;border:1px so" +
                    "lid #EBEBEB;overflow:hidden;width:600px;border-radius:3px 3px 3px 3px;\">\r\n<!--<!" +
                    "[endif]-->\r\n<table class=t63 role=presentation cellpadding=0 cellspacing=0 width" +
                    "=100% style=\"width:100%;\"><tr>\r\n<td class=t62 style=\"padding:44px 42px 32px 42px" +
                    ";\"><table role=presentation width=100% cellpadding=0 cellspacing=0 style=\"width:" +
                    "100% !important;\"><tr><td align=left>\r\n<table class=t4 role=presentation cellpad" +
                    "ding=0 cellspacing=0 style=\"Margin-right:auto;\">\r\n<tr>\r\n<!--[if mso]>\r\n<td width" +
                    "=42 class=t3 style=\"overflow:hidden;width:42px;border-radius:99px 99px 99px 99px" +
                    ";\">\r\n<![endif]-->\r\n<!--[if !mso]>-->\r\n<td class=t3 style=\"overflow:hidden;width:" +
                    "42px;border-radius:99px 99px 99px 99px;\">\r\n<!--<![endif]-->\r\n<table class=t2 rol" +
                    "e=presentation cellpadding=0 cellspacing=0 width=100% style=\"width:100%;\"><tr>\r\n" +
                    "<td class=t1><div style=\"font-size:0px;\"><img class=\"t0\" style=\"display:block;bo" +
                    "rder:0;height:auto;width:100%;Margin:0;max-width:100%;\" width=\"42\" height=\"42\" a" +
                    "lt=\"\" src=\"https://uploads.tabular.email/u/94b7e03e-ef53-4710-90c3-f2b662ad7995/" +
                    "6f09beeb-e7ac-4e41-a214-007a437a193f.png\"></div></td>\r\n</tr></table>\r\n</td>\r\n</t" +
                    "r></table>\r\n</td></tr><tr><td><div class=t5 style=\"mso-line-height-rule:exactly;" +
                    "mso-line-height-alt:42px;line-height:42px;font-size:1px;display:block;\">&nbsp;&n" +
                    "bsp;</div></td></tr><tr><td align=center>\r\n<table class=t10 role=presentation ce" +
                    "llpadding=0 cellspacing=0 style=\"Margin-left:auto;Margin-right:auto;\">\r\n<tr>\r\n<!" +
                    "--[if mso]>\r\n<td width=514 class=t9 style=\"border-bottom:1px solid #EFF1F4;width" +
                    ":514px;\">\r\n<![endif]-->\r\n<!--[if !mso]>-->\r\n<td class=t9 style=\"border-bottom:1p" +
                    "x solid #EFF1F4;width:514px;\">\r\n<!--<![endif]-->\r\n<table class=t8 role=presentat" +
                    "ion cellpadding=0 cellspacing=0 width=100% style=\"width:100%;\"><tr>\r\n<td class=t" +
                    "7 style=\"padding:0 0 18px 0;\"><h1 class=t6 style=\"margin:0;Margin:0;font-family:" +
                    "Montserrat,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-heig" +
                    "ht:28px;font-weight:700;font-style:normal;font-size:24px;text-decoration:none;te" +
                    "xt-transform:none;letter-spacing:-1px;direction:ltr;color:#141414;text-align:lef" +
                    "t;mso-line-height-rule:exactly;mso-text-raise:1px;\">");
            
            #line 169 "D:\Business\socigy\server\microservices\Socigy.Microservices.Auth\Resources\EmailTemplates\CodeVerificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Title));
            
            #line default
            #line hidden
            this.Write(@"</h1></td>
</tr></table>
</td>
</tr></table>
</td></tr><tr><td><div class=t11 style=""mso-line-height-rule:exactly;mso-line-height-alt:18px;line-height:18px;font-size:1px;display:block;"">&nbsp;&nbsp;</div></td></tr><tr><td align=center>
<table class=t17 role=presentation cellpadding=0 cellspacing=0 style=""Margin-left:auto;Margin-right:auto;"">
<tr>
<!--[if mso]>
<td width=514 class=t16 style=""width:514px;"">
<![endif]-->
<!--[if !mso]>-->
<td class=t16 style=""width:514px;"">
<!--<![endif]-->
<table class=t15 role=presentation cellpadding=0 cellspacing=0 width=100% style=""width:100%;""><tr>
<td class=t14><p class=t13 style=""margin:0;Margin:0;font-family:Open Sans,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:25px;font-weight:400;font-style:normal;font-size:15px;text-decoration:none;text-transform:none;letter-spacing:-0.1px;direction:ltr;color:#141414;text-align:left;mso-line-height-rule:exactly;mso-text-raise:3px;"">");
            
            #line 183 "D:\Business\socigy\server\microservices\Socigy.Microservices.Auth\Resources\EmailTemplates\CodeVerificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Description));
            
            #line default
            #line hidden
            this.Write(". The link and code are valid for <span class=t12 style=\"margin:0;Margin:0;font-w" +
                    "eight:700;mso-line-height-rule:exactly;\">");
            
            #line 183 "D:\Business\socigy\server\microservices\Socigy.Microservices.Auth\Resources\EmailTemplates\CodeVerificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CodeLifespan));
            
            #line default
            #line hidden
            this.Write(@" hours</span>.</p></td>
</tr></table>
</td>
</tr></table>
</td></tr><tr><td><div class=t18 style=""mso-line-height-rule:exactly;mso-line-height-alt:40px;line-height:40px;font-size:1px;display:block;"">&nbsp;&nbsp;</div></td></tr><tr><td><div class=t21 style=""mso-line-height-rule:exactly;mso-line-height-alt:15px;line-height:15px;font-size:1px;display:block;"">&nbsp;&nbsp;</div></td></tr><tr><td align=center>
<table class=t25 role=presentation cellpadding=0 cellspacing=0 style=""Margin-left:auto;Margin-right:auto;"">
<tr>
<!--[if mso]>
<td class=t24 style=""width:auto;"">
<![endif]-->
<!--[if !mso]>-->
<td class=t24 style=""width:auto;"">
<!--<![endif]-->
<table class=t23 role=presentation cellpadding=0 cellspacing=0 style=""width:auto;""><tr>
<td class=t22><p class=t20 style=""margin:0;Margin:0;font-family:Open Sans,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:25px;font-weight:400;font-style:normal;font-size:50px;text-decoration:none;text-transform:none;letter-spacing:-0.1px;direction:ltr;color:#141414;text-align:left;mso-line-height-rule:exactly;mso-text-raise:-7px;""><span class=t19 style=""margin:0;Margin:0;font-weight:700;mso-line-height-rule:exactly;"">");
            
            #line 197 "D:\Business\socigy\server\microservices\Socigy.Microservices.Auth\Resources\EmailTemplates\CodeVerificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Code));
            
            #line default
            #line hidden
            this.Write(@"</span></p></td>
</tr></table>
</td>
</tr></table>
</td></tr><tr><td><div class=t27 style=""mso-line-height-rule:exactly;mso-line-height-alt:40px;line-height:40px;font-size:1px;display:block;"">&nbsp;&nbsp;</div></td></tr><tr><td align=center>
<table class=t31 role=presentation cellpadding=0 cellspacing=0 style=""Margin-left:auto;Margin-right:auto;"">
<tr>
<!--[if mso]>
<td class=t30 style=""background-color:#000000;overflow:hidden;width:auto;border-radius:40px 40px 40px 40px;"">
<![endif]-->
<!--[if !mso]>-->
<td class=t30 style=""background-color:#000000;overflow:hidden;width:auto;border-radius:40px 40px 40px 40px;"">
    <a href=""");
            
            #line 209 "D:\Business\socigy\server\microservices\Socigy.Microservices.Auth\Resources\EmailTemplates\CodeVerificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UrlLink));
            
            #line default
            #line hidden
            this.Write(@""">
        <!--<![endif]-->
        <table class=t29 role=presentation cellpadding=0 cellspacing=0 style=""width:auto;""><tr>
        <td class=t28 style=""text-align:center;line-height:34px;mso-line-height-rule:exactly;mso-text-raise:5px;padding:5px 25px 5px 25px;cursor: pointer;-webkit-user-select: none;-ms-user-select: none;user-select: none;""><span class=t26 style=""display:block;margin:0;Margin:0;font-family:Sofia Sans,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:34px;font-weight:700;font-style:normal;font-size:16px;text-decoration:none;text-transform:none;letter-spacing:-0.2px;direction:ltr;color:#FFFFFF;text-align:center;mso-line-height-rule:exactly;mso-text-raise:5px;"">");
            
            #line 212 "D:\Business\socigy\server\microservices\Socigy.Microservices.Auth\Resources\EmailTemplates\CodeVerificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ButtonText));
            
            #line default
            #line hidden
            this.Write(@"</span></td>
        </tr></table>
    </a>
</td>
</tr></table>
</td></tr><tr><td><div class=t32 style=""mso-line-height-rule:exactly;mso-line-height-alt:10px;line-height:10px;font-size:1px;display:block;"">&nbsp;&nbsp;</div></td></tr><tr><td align=center>
<table class=t38 role=presentation cellpadding=0 cellspacing=0 style=""Margin-left:auto;Margin-right:auto;"">
<tr>
<!--[if mso]>
<td class=t37 style=""width:auto;"">
<![endif]-->
<!--[if !mso]>-->
<td class=t37 style=""width:auto;"">
<!--<![endif]-->
<table class=t36 role=presentation cellpadding=0 cellspacing=0 style=""width:auto;""><tr>
<td class=t35><p class=t34 style=""margin:0;Margin:0;font-family:Open Sans,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:25px;font-weight:400;font-style:normal;font-size:15px;text-decoration:none;text-transform:none;letter-spacing:-0.1px;direction:ltr;color:#141414;text-align:left;mso-line-height-rule:exactly;mso-text-raise:3px;""><a class=t33 href=""");
            
            #line 227 "D:\Business\socigy\server\microservices\Socigy.Microservices.Auth\Resources\EmailTemplates\CodeVerificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UrlLink));
            
            #line default
            #line hidden
            this.Write("\" style=\"margin:0;Margin:0;font-weight:400;font-style:normal;text-decoration:none" +
                    ";direction:ltr;color:#3381F6;mso-line-height-rule:exactly;\" target=_blank>");
            
            #line 227 "D:\Business\socigy\server\microservices\Socigy.Microservices.Auth\Resources\EmailTemplates\CodeVerificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LinkText));
            
            #line default
            #line hidden
            this.Write(@"</a></p></td>
</tr></table>
</td>
</tr></table>
</td></tr><tr><td><div class=t43 style=""mso-line-height-rule:exactly;mso-line-height-alt:30px;line-height:30px;font-size:1px;display:block;"">&nbsp;&nbsp;</div></td></tr><tr><td align=center>
<table class=t47 role=presentation cellpadding=0 cellspacing=0 style=""Margin-left:auto;Margin-right:auto;"">
<tr>
<!--[if mso]>
<td width=514 class=t46 style=""width:514px;"">
<![endif]-->
<!--[if !mso]>-->
<td class=t46 style=""width:514px;"">
<!--<![endif]-->
<table class=t45 role=presentation cellpadding=0 cellspacing=0 width=100% style=""width:100%;""><tr>
<td class=t44><p class=t42 style=""margin:0;Margin:0;font-family:Open Sans,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:25px;font-weight:400;font-style:normal;font-size:15px;text-decoration:none;text-transform:none;letter-spacing:-0.1px;direction:ltr;color:#141414;text-align:left;mso-line-height-rule:exactly;mso-text-raise:3px;"">");
            
            #line 241 "D:\Business\socigy\server\microservices\Socigy.Microservices.Auth\Resources\EmailTemplates\CodeVerificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EndDescription));
            
            #line default
            #line hidden
            this.Write(". For security purposes, the link will expire in <span class=t39 style=\"margin:0;" +
                    "Margin:0;font-weight:700;mso-line-height-rule:exactly;\">");
            
            #line 241 "D:\Business\socigy\server\microservices\Socigy.Microservices.Auth\Resources\EmailTemplates\CodeVerificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CodeLifespan));
            
            #line default
            #line hidden
            this.Write(" hours</span>. If you have any concerns or need further assistance, feel free to " +
                    "reach out to our support team at <span class=t41 style=\"margin:0;Margin:0;mso-li" +
                    "ne-height-rule:exactly;\"><span class=t40 style=\"margin:0;Margin:0;font-weight:70" +
                    "0;mso-line-height-rule:exactly;\">support@socigy.com</span></span></p></td>\r\n</tr" +
                    "></table>\r\n</td>\r\n</tr></table>\r\n</td></tr><tr><td><div class=t56 style=\"mso-lin" +
                    "e-height-rule:exactly;mso-line-height-alt:40px;line-height:40px;font-size:1px;di" +
                    "splay:block;\">&nbsp;&nbsp;</div></td></tr><tr><td align=center>\r\n<table class=t6" +
                    "0 role=presentation cellpadding=0 cellspacing=0 style=\"Margin-left:auto;Margin-r" +
                    "ight:auto;\">\r\n<tr>\r\n<!--[if mso]>\r\n<td width=514 class=t59 style=\"border-top:1px" +
                    " solid #DFE1E4;width:514px;\">\r\n<![endif]-->\r\n<!--[if !mso]>-->\r\n<td class=t59 st" +
                    "yle=\"border-top:1px solid #DFE1E4;width:514px;\">\r\n<!--<![endif]-->\r\n<table class" +
                    "=t58 role=presentation cellpadding=0 cellspacing=0 width=100% style=\"width:100%;" +
                    "\"><tr>\r\n<td class=t57 style=\"padding:24px 0 0 0;\"><div class=t55 style=\"width:10" +
                    "0%;text-align:left;\"><div class=t54 style=\"display:inline-block;\"><table class=t" +
                    "53 role=presentation cellpadding=0 cellspacing=0 align=left valign=top>\r\n<tr cla" +
                    "ss=t52><td></td><td class=t51 width=514 valign=top>\r\n<table role=presentation wi" +
                    "dth=100% cellpadding=0 cellspacing=0 class=t50 style=\"width:100%;\"><tr>\r\n<td cla" +
                    "ss=t49><p class=t48 style=\"margin:0;Margin:0;font-family:Open Sans,BlinkMacSyste" +
                    "mFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:25px;font-weight:400;" +
                    "font-style:normal;font-size:15px;text-decoration:none;text-transform:none;letter" +
                    "-spacing:-0.1px;direction:ltr;color:#141414;text-align:left;mso-line-height-rule" +
                    ":exactly;mso-text-raise:3px;\">Best regards, <br/>The Socigy Team</p></td>\r\n</tr>" +
                    "</table>\r\n</td>\r\n<td></td></tr>\r\n</table></div></div></td>\r\n</tr></table>\r\n</td>" +
                    "\r\n</tr></table>\r\n</td></tr></table></td>\r\n</tr></table>\r\n</td>\r\n</tr></table>\r\n<" +
                    "/td></tr><tr><td><div class=t66 style=\"mso-line-height-rule:exactly;mso-line-hei" +
                    "ght-alt:50px;line-height:50px;font-size:1px;display:block;\">&nbsp;&nbsp;</div></" +
                    "td></tr></table></td></tr></table></div><div class=\"gmail-fix\" style=\"display: n" +
                    "one; white-space: nowrap; font: 15px courier; line-height: 0;\">&nbsp; &nbsp; &nb" +
                    "sp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;" +
                    " &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &n" +
                    "bsp; &nbsp; &nbsp; &nbsp; &nbsp;</div></body>\r\n</html>\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 272 "D:\Business\socigy\server\microservices\Socigy.Microservices.Auth\Resources\EmailTemplates\CodeVerificationTemplate.tt"

		public string Title;
		public string Description;
		public string Code;
		public string UrlLink;
		public string EndDescription;
		public string ButtonText;
		public string LinkText;
		public byte CodeLifespan;

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class CodeVerificationTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
